# Generated by Django 4.1.4 on 2022-12-15 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StrudentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastName', models.CharField(max_length=250)),
                ('firstName', models.CharField(max_length=250)),
                ('phone_number', models.TextField()),
                ('b_day', models.DateTimeField()),
            ],
        ),
    ]
