# Generated by Django 4.1.4 on 2022-12-15 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_strudentinfo_lastname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strudentinfo',
            name='b_day',
            field=models.DateField(),
        ),
    ]
