# Generated by Django 4.1.4 on 2022-12-24 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_course_delete_strudentinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.TextField()),
                ('image', models.ImageField(null=True, upload_to='')),
                ('teaching_course', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
    ]
